services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "your_user", "-d", "your_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
      POSTGRES_HOST: postgres
      TEMPLATE_DIR: "/app/internal/templates"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8086:8086"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
