name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build and tag Docker image
        run: docker build -t archive:latest .

      # Step 4: Configure SSH
      - name: Set up SSH known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.DIGITALOCEAN_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # Step 5: Push image to droplet
      - name: Deploy to DigitalOcean Droplet
        env:
          DIGITALOCEAN_IP: ${{ secrets.DIGITALOCEAN_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key
          
          # Transfer the Docker image to the droplet
          docker save archive:latest | ssh -v -i private_key ${SSH_USERNAME}@${DIGITALOCEAN_IP} "docker load"
          
          # Restart the app container on the droplet
          ssh -i private_key ${SSH_USERNAME}@${DIGITALOCEAN_IP} << EOF
            docker stop archive || true
            docker rm archive || true
            docker run -d --name archive -p 8080:8087 archive:latest
          EOF
          
          # Clean up
          rm private_key
